### ISSUE TITLE
how are would it be to drop maple bootloader and use stm32duino from stmicroelectronic?

### ISSUE THREAD

**Issue by ricoelmostico** [arpruss/gamecube-usb-adapter#2]
Hello, I want to implement this project but I already use my bluepill with stm32duino from stmicroelectronic and not maple bootloader.
As maple bootloader is old and not as maintained as stm32duino from stmicroelectronic, would it be possible to port this project so it won't use maple lib or USB HID.h.
This would make it future proof.
Thank you for your time.

**Comment by arpruss** [comment]
It's possible, but it's not easy. You're welcome to do it. I believe all the core-dependent code is gathered in usb_generic.[ch]. 

I have to confess I have little interest in learning about the stm32duino core myself, unless someone pays me to do it, since libmaple likely makes for more efficient code due to less bloat, and is a very reliable and quite well-tested core.

**Comment by arpruss** [comment]
It could be done, no doubt, but would be a lot of work. And it works just fine as it stands with the libmaple core, which has less bloat than the official core, and is extremely reliable.
